name: discord_voice_notification
on: workflow_dispatch
# on:
#   schedule:
# 定期実行する時間
# - cron: "15 * * * *"
jobs:
  npm_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
  create_env:
    runs-on: ubuntu-latest
    steps:
      - run: |
          touch .env
          echo "TOKEN=${{ secrets.TOKEN }}" >> .env
          echo "VOICE_CHANNEL_ID=${{ secrets.VOICE_CHANNEL_ID }}" >> .env
          echo "MESSAGE_CHANNEL_ID=${{ secrets.MESSAGE_CHANNEL_ID }}" >> .env
  start_watch_channel:
    runs-on: ubuntu-latest
    needs: [npm_build, create_env]
    steps:
      - run: node voice_notification/voiceMemberNotification.js
