name: send_message
on:
  # 手動での実行
  workflow_dispatch:
    inputs:
      message:
        type: string
        required: true
        description: "通知したいメッセージを入力してください"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Create dot env file
        run: |
          touch .env
          echo "TOKEN=${{ secrets.TOKEN }}" >> .env
          echo "MESSAGE_CHANNEL_ID=${{ secrets.MESSAGE_CHANNEL_ID }}" >> .env
      - run: npm install
      - name: Send Messege
        env:
          INPUT_TEXT: ${{ github.event.inputs.message }}
        run: node src/sendMessage.js "${INPUT_TEXT}"
        timeout-minutes: 1
